# Generated by Django 6.0 on 2025-12-26 05:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0002_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
