# Generated by Django 6.0 on 2026-07-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0005_message_is_read_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_messages_multi', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_messages', to='auth.user'),
        ),
    ]
