# Generated by Django 6.0 on 2026-07-29 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0006_message_recipients_alter_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
